import {
  Activity,
  CheckCircle2,
  Clock3,
  Code2,
  LoaderCircle,
  XCircle,
} from "lucide-react";

function formatTime(value) {
  if (!value) return "--:--:--";

  const date = new Date(value);

  if (Number.isNaN(date.getTime())) {
    return "--:--:--";
  }

  return date.toLocaleTimeString();
}

function formatToolName(tool) {
  if (!tool) return "Unknown tool";

  return tool
    .replace(/^ripple_/, "")
    .replaceAll("_", " ")
    .replace(/\b\w/g, (letter) => letter.toUpperCase());
}

function StatusIcon({ status }) {
  if (status === "success") {
    return (
      <CheckCircle2
        size={15}
        className="text-emerald-400"
      />
    );
  }

  if (status === "error") {
    return (
      <XCircle
        size={15}
        className="text-red-400"
      />
    );
  }

  return (
    <LoaderCircle
      size={15}
      className="animate-spin text-violet-400"
    />
  );
}

export default function BobPanel({
  activity = [],
  latestEvent,
  integrationStatus,
  repositoryName,
  lastUpdated,
}) {
  const connected =
    integrationStatus === "connected" ||
    integrationStatus === "online";

  return (
    <div className="flex min-h-[680px] flex-col overflow-hidden rounded-2xl border border-white/[0.08] bg-[#0d1219]">
      {/* Header */}
      <div className="border-b border-white/[0.08] px-5 py-5">
        <div className="flex items-center justify-between gap-4">
          <div className="flex items-center gap-3">
            <div className="flex h-10 w-10 items-center justify-center rounded-xl border border-violet-400/20 bg-violet-500/10">
              <Activity
                size={18}
                className="text-violet-400"
              />
            </div>

            <div>
              <div className="flex items-center gap-2">
                <h2 className="text-[15px] font-semibold text-white">
                  Live MCP Activity
                </h2>

                <span
                  className={`rounded-full border px-2 py-0.5 text-[9px] font-semibold uppercase tracking-[0.08em] ${
                    connected
                      ? "border-emerald-400/15 bg-emerald-400/[0.06] text-emerald-400"
                      : "border-amber-400/15 bg-amber-400/[0.06] text-amber-400"
                  }`}
                >
                  {connected ? "Connected" : "Offline"}
                </span>
              </div>

              <p className="mt-1 text-[11px] text-zinc-500">
                Ripple backend activity generated by Bob.
              </p>
            </div>
          </div>

          <div className="hidden items-center gap-2 text-[10px] text-zinc-600 sm:flex">
            <Clock3 size={12} />

            {lastUpdated
              ? formatTime(lastUpdated)
              : "Waiting"}
          </div>
        </div>
      </div>

      {/* Latest request */}
      <div className="border-b border-white/[0.08] p-5">
        <div className="mb-3 text-[10px] font-semibold uppercase tracking-[0.14em] text-zinc-500">
          Latest request
        </div>

        {latestEvent ? (
          <div className="rounded-xl border border-violet-400/15 bg-violet-500/[0.04] p-4">
            <div className="flex items-start gap-3">
              <div className="mt-0.5 flex h-8 w-8 shrink-0 items-center justify-center rounded-lg border border-violet-400/15 bg-violet-500/10">
                <StatusIcon status={latestEvent.status} />
              </div>

              <div className="min-w-0 flex-1">
                <div className="text-[13px] font-semibold text-zinc-100">
                  {formatToolName(latestEvent.tool)}
                </div>

                <div className="mt-1 text-[11px] leading-5 text-zinc-400">
                  {latestEvent.message ||
                    "Ripple processed an MCP request."}
                </div>

                <div className="mt-2 flex flex-wrap gap-3 text-[10px] text-zinc-600">
                  <span>
                    {formatTime(latestEvent.timestamp)}
                  </span>

                  {latestEvent.duration_ms != null && (
                    <span>
                      {latestEvent.duration_ms} ms
                    </span>
                  )}

                  {repositoryName && (
                    <span>
                      {repositoryName}
                    </span>
                  )}
                </div>
              </div>
            </div>
          </div>
        ) : (
          <div className="rounded-xl border border-white/[0.08] bg-white/[0.02] px-4 py-6 text-center">
            <Code2
              size={18}
              className="mx-auto text-zinc-600"
            />

            <p className="mt-2 text-[11px] text-zinc-500">
              No MCP requests have been recorded yet.
            </p>

            <p className="mt-1 text-[10px] text-zinc-600">
              Activity will appear here when Bob calls Ripple.
            </p>
          </div>
        )}
      </div>

      {/* Activity stream */}
      <div className="flex-1 overflow-y-auto p-5">
        <div className="mb-3 text-[10px] font-semibold uppercase tracking-[0.14em] text-zinc-500">
          Request stream
        </div>

        {activity.length === 0 ? (
          <div className="flex min-h-[300px] items-center justify-center rounded-xl border border-dashed border-white/[0.08] bg-white/[0.015]">
            <div className="text-center">
              <Activity
                size={20}
                className="mx-auto text-zinc-700"
              />

              <div className="mt-3 text-[12px] font-medium text-zinc-500">
                Waiting for Bob
              </div>

              <div className="mt-1 text-[10px] text-zinc-600">
                MCP tool calls will appear here in real time.
              </div>
            </div>
          </div>
        ) : (
          <div className="space-y-2">
            {activity.map((event) => (
              <div
                key={event.id}
                className="rounded-xl border border-white/[0.07] bg-white/[0.02] p-3.5"
              >
                <div className="flex items-center gap-3">
                  <StatusIcon status={event.status} />

                  <div className="min-w-0 flex-1">
                    <div className="truncate text-[12px] font-medium text-zinc-200">
                      {formatToolName(event.tool)}
                    </div>

                    <div className="mt-0.5 truncate text-[10px] text-zinc-500">
                      {event.message ||
                        "MCP request completed."}
                    </div>
                  </div>

                  <div className="shrink-0 text-right">
                    <div className="text-[9px] text-zinc-600">
                      {formatTime(event.timestamp)}
                    </div>

                    {event.duration_ms != null && (
                      <div className="mt-0.5 text-[9px] text-zinc-700">
                        {event.duration_ms}ms
                      </div>
                    )}
                  </div>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* Footer */}
      <div className="border-t border-white/[0.08] px-5 py-4">
        <div className="flex items-center justify-between gap-3">
          <div className="text-[10px] text-zinc-600">
            Showing the latest {activity.length} MCP events
          </div>

          <div className="flex items-center gap-2 text-[10px] text-emerald-400">
            <span className="h-1.5 w-1.5 rounded-full bg-emerald-400" />
            Live
          </div>
        </div>
      </div>
    </div>
  );
}